User updating
Programming-Engineering-Pmi-31/YNote pull request #39
Opened 2019-12-10 21:59 UTC by nazar110

2019-12-10 23:25 UTC, FoxLviv requested changes

2019-12-10 23:25 UTC, FoxLviv commented on YNoteWPF.PL/MainWindow.xaml.cs
> +>>>>>>> cfcf0adac9e9034abafbf8911e36d40a85ac20a4
Fix conflicts

2019-12-10 23:25 UTC, FoxLviv commented on YNoteWPF.PL/MainWindow.xaml.cs
> +=======
Fix conflicts

2019-12-10 23:25 UTC, FoxLviv commented on YNoteWPF.PL/MainWindow.xaml.cs
> +<<<<<<< HEAD
Fix conflicts

2019-12-10 23:25 UTC, FoxLviv commented on YNoteWPF.PL/MainWindow.xaml.cs
> +>>>>>>> cfcf0adac9e9034abafbf8911e36d40a85ac20a4
Fix conflicts

2019-12-10 23:25 UTC, FoxLviv commented on YNoteWPF.PL/MainWindow.xaml.cs
> +=======
Fix conflicts

2019-12-10 23:25 UTC, FoxLviv commented on YNoteWPF.PL/MainWindow.xaml.cs
> +<<<<<<< HEAD
Fix conflicts

2019-12-10 23:25 UTC, FoxLviv commented on YNoteWPF.PL/MainWindow.xaml.cs
> +>>>>>>> cfcf0adac9e9034abafbf8911e36d40a85ac20a4
Fix conflicts

2019-12-10 23:25 UTC, FoxLviv commented on YNoteWPF.PL/MainWindow.xaml.cs
> +<<<<<<< HEAD
Fix conflicts

2019-12-10 23:25 UTC, FoxLviv commented on YNoteWPF.PL/MainWindow.xaml.cs
> +=======
Fix conflicts

2019-12-11 10:28 UTC, nazar110 commented on YNoteWPF.PL/MainWindow.xaml.cs
> +>>>>>>> cfcf0adac9e9034abafbf8911e36d40a85ac20a4
Done

2019-12-11 10:28 UTC, nazar110 commented on YNoteWPF.PL/MainWindow.xaml.cs
> +=======
Done

2019-12-11 10:28 UTC, nazar110 commented on YNoteWPF.PL/MainWindow.xaml.cs
> +<<<<<<< HEAD
Done

2019-12-11 10:28 UTC, nazar110 commented on YNoteWPF.PL/MainWindow.xaml.cs
> +>>>>>>> cfcf0adac9e9034abafbf8911e36d40a85ac20a4
Done

2019-12-11 10:28 UTC, nazar110 commented on YNoteWPF.PL/MainWindow.xaml.cs
> +=======
Done

2019-12-11 10:29 UTC, nazar110 commented on YNoteWPF.PL/MainWindow.xaml.cs
> +<<<<<<< HEAD
Done

2019-12-11 10:29 UTC, nazar110 commented on YNoteWPF.PL/MainWindow.xaml.cs
> +>>>>>>> cfcf0adac9e9034abafbf8911e36d40a85ac20a4
Done

2019-12-11 10:29 UTC, nazar110 commented on YNoteWPF.PL/MainWindow.xaml.cs
> +<<<<<<< HEAD
Done

2019-12-11 10:29 UTC, nazar110 commented on YNoteWPF.PL/MainWindow.xaml.cs
> +=======
Done

2019-12-12 11:32 UTC, FoxLviv commented
reviewed

2019-12-12 21:57 UTC, merged